### ISSUE TITLE
doesn't work on redm

### ISSUE THREAD

**Issue by midoom** [kibook/popdensity#1]
hello, doesn't work on redm, nothing happened

**Comment by kibook** [comment]
In my testing, it does seem to have an effect on the amount of population peds spawned, but unlike in FiveM, 0.0 doesn't seem to completely remove all peds. This may be because there isn't an equivalent to `SetPedDensityMultiplierThisFrame` known yet for RedM, so only `SetScenarioPedDensityMultiplierThisFrame` is set.

**Comment by kibook** [comment]
In 4440c76, I added the other known multipliers for RedM:
- `SetAmbientAnimalDensityMultiplierThisFrame`
- `SetAmbientHumanDensityMultiplierThisFrame`
- `SetAmbientPedDensityMultiplierThisFrame`
- `SetScenarioAnimalDensityMultiplierThisFrame`
- `SetScenarioHumanDensityMultiplierThisFrame`

As far as I can tell this is everything, and `0.0` means absolutely no peds now for RedM too.
